### ISSUE TITLE
Need to be able to define the spi chip model from the yaml file instead of hardcoding in ctrl.go

### ISSUE THREAD

**Issue by gregg-shick** [opencomputeproject/OSF-OSFCI#102]
BMC_CHIP: "MX25L25635E"
BIOS_CHIP: "W25Q256JV"

**Comment by arunkoshy** [comment]
working on this @gregg-shick - there was some old work on this by @susmithp that was never merged - we will do a fresh take and get @vejmarie  to review / merge
