### ISSUE TITLE
Provide dynamic help via UX.

### ISSUE THREAD

**Issue by arunkoshy** [opencomputeproject/OSF-OSFCI#13]
based on feedback from @rminnich , we will have a faster tutorial style introduction for osfci.tech

**Comment by vejmarie** [comment]
there is a work in progress page available into #Features accessible from the front page. It is not finished and clean , but that could be a good initial start to look at. Other option would be to put in place a walk through when the session open. That is doable with bootstrap and using popups.

**Comment by arunkoshy** [comment]
@vejmarie good point -- I will refactor top title bar to change

" Features " to " Help " 
" How to help " to " Contribute "

This will make it more clearer for more folks while we work on refactoring / refining the tutorial

**Comment by arunkoshy** [comment]
based on discussion with @vejmarie and @susmithp , we have decided to:

1. provide dynamic tool-tip help that will be offered to user in real-time
2. help can be toggled via checkbox

**Comment by arunkoshy** [comment]
This was deployed a while back !
