### ISSUE TITLE
Fixes for compiler service failures when using an invalid OpenBMC repo

### ISSUE THREAD

**Issue by susmithp** [opencomputeproject/OSF-OSFCI#19]
Complier services fail with the below error messages when a customer used an OpenBMC invalid repo to build the image.

runtime error: index out of range [3] with length 3.

**Comment by csides-hpe** [comment]
Related issue: compiler services fail with _no_ output message (output window is left empty) if a **valid OpenBMC repo is specified with an invalid branch** name specified.
