### ISSUE TITLE
Missing tools in PATH error when building from latest mainstream OpenBMC repo

### ISSUE THREAD

**Issue by csides-hpe** [opencomputeproject/OSF-OSFCI#51]
Got an error about missing tools ' lz4c pzstd zstd' when trying to build the latest mainstream OpenBMC repo with private-OSFCI (issue likely also exist in public-OSFCI)

![image](https://user-images.githubusercontent.com/99367432/177857757-8f75b229-f533-4fdf-b779-ccdac157e058.png)

-- url used --

https://github.com/openbmc/openbmc.git master

**Comment by arunkoshy** [comment]
@vejmarie @susmithp @gregg-shick  any comments here ?

**Comment by gregg-shick** [comment]
Container needs to be updated with those additonal packages it looks like.

**Comment by arunkoshy** [comment]
based on discussion with @vejmarie , @susmithp and @gregg-shick .. will be doing some mods on https://github.com/opencomputeproject/OSF-OSFCI/blob/master/compile/Dockerfile.openbmc to fix this
