### ISSUE TITLE
Add support to get the bios serial boot logs

### ISSUE THREAD

**Issue by susmithp** [opencomputeproject/OSF-OSFCI#57]
We need to provide an option for users to download the bios serial logs.

ssh into an openbmc @port 2200 and reboot server

**Comment by arunkoshy** [comment]
work on this kicked off today. Basic pathway is clear re manual steps to retrieve these logs.

**Comment by gregg-shick** [comment]
A request has come in to also grab the openbmc console output as well.

**Comment by arunkoshy** [comment]
thanks @gregg-shick - we will add.

**Comment by arunkoshy** [comment]
based on internal discussions, we will tackle the openbmc console requirement seperately.

**Comment by arunkoshy** [comment]
status: tackling some debug issues on collection sequence that is beyond the scope of this ticket.

**Comment by arunkoshy** [comment]
status: issue is facing a blocker due to collection reliability. Will resolve once we clear that out.

**Comment by gregg-shick** [comment]
My thoughts

1.  As soon as connect power is done, begin logging the 2200 session.
2.  Present the user with an interface option to download the bios serial log once session is established. 
3.  User can do whatever he chooses in the session, including powering on the unit from the openbmc web interface.
4.  It is then up to the user to download bios serial log before sessions times out or session is ended by user.   
5.  Clean up logs at session closure.

**Comment by arunkoshy** [comment]
yep, agreed @gregg-shick - we now no longer worry about anything beyond logging the 2200 session.
