### ISSUE TITLE
Public OSFCI doesn't show 'BMC web' when loading a ROM built from hewlettpackard/openbmc

### ISSUE THREAD

**Issue by csides-hpe** [opencomputeproject/OSF-OSFCI#59]
Public OSFCI doesn't show the 'BMC web' connect buttons when using an image built from 'https://github.com/HewlettPackard/openbmc.git dev-gxp' for the DL360 G10. 

If I have OSFCI build from the URL, the build completes, and image seems to load fine. When I click 'connect power' it appears to load normally, and briefly shows a 'login:' prompt at some point, indicating it made it _that far_ at least. 

![image](https://user-images.githubusercontent.com/99367432/184708307-92a5ee0b-c791-41a9-ae5d-4cb84178f7a6.png)

I have been unable to test this out on the private OSFCI due to an issue with loading a ROM image (submitted as a separate, third issue).

The buttons do show up if I just click the 'load standard OpenBMC' button instead of building or loading my own images.

![image](https://user-images.githubusercontent.com/99367432/184708632-876b9678-66c2-49c2-a626-4bad8c36216d.png)
(this last screenshot is from a dl325, but this works for a dl360 too)

**Comment by arunkoshy** [comment]
This seems to have been resolved -- attaching my run of things.
![Chris-Error-1](https://user-images.githubusercontent.com/1412929/190685953-a7f1f640-896f-4d08-9bc9-dd2da0795447.png)
![Chris-Error-2](https://user-images.githubusercontent.com/1412929/190685956-25a5b2b3-c641-46ed-8d18-f280351efadc.png)
