### ISSUE TITLE
OSFCI (private): 'Could not claim interface' when loading a BIOS

### ISSUE THREAD

**Issue by csides-hpe** [opencomputeproject/OSF-OSFCI#60]
When I try to load a BIOS on the private OSFCI (DL360 G10), I get the following error output:

>Address offset: 0xfe0000000
>Could not claim interface.
>Could not find EM100 pro with serial number EM144924

I've been seeing this error since at least late last week, both when clicking 'load standard bios' or when drag-n-drop uploading a saved copy of the DL360 G10 standard bios file.

**Comment by arunkoshy** [comment]
This happens at times when the EM100s go offline. Fixed with resets ( hard / soft ).
